<!-- resources/views/pdf/submission.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>OJT Report - {{ $submission->title }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; }
        .header { text-align: center; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; color: #333; }
        .subtitle { font-size: 16px; color: #666; margin-top: 5px; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 18px; font-weight: bold; margin-bottom: 10px; color: #4F46E5; }
        .info-row { margin-bottom: 10px; }
        .label { font-weight: bold; display: inline-block; width: 150px; }
        .status { padding: 5px 10px; border-radius: 5px; display: inline-block; }
        .status-pending { background-color: #FEF3C7; color: #92400E; }
        .status-approved { background-color: #D1FAE5; color: #065F46; }
        .status-rejected { background-color: #FEE2E2; color: #991B1B; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">On-the-Job Training Report</div>
        <div class="subtitle">Weekly Progress Report</div>
    </div>

    <div class="section">
        <div class="section-title">Report Information</div>
        <div class="info-row">
            <span class="label">Report Title:</span>
            <span>{{ $submission->title }}</span>
        </div>
        <div class="info-row">
            <span class="label">Submitted Date:</span>
            <span>{{ $submission->submitted_at ? $submission->submitted_at->format('F d, Y') : 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="label">Status:</span>
            <span class="status status-{{ $submission->status }}">
                {{ ucfirst($submission->status) }}
            </span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Student Information</div>
        <div class="info-row">
            <span class="label">Student Name:</span>
            <span>{{ $submission->student->name }}</span>
        </div>
        <div class="info-row">
            <span class="label">Student ID:</span>
            <span>{{ $submission->student->student_id ?? 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="label">Department:</span>
            <span>{{ $submission->student->department ?? 'N/A' }}</span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">Report Details</div>
        <div class="info-row">
            <span class="label">Folder:</span>
            <span>{{ $submission->folder->name }}</span>
        </div>
        <div class="info-row">
            <span class="label">Description:</span>
            <p>{{ $submission->description }}</p>
        </div>
    </div>

    @if($submission->supervisor_feedback || $submission->supervisor)
    <div class="section">
        <div class="section-title">Supervisor Approval Proof</div>
        <div class="info-row">
            <span class="label">Supervisor:</span>
            <span>{{ $submission->supervisor->name ?? 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="label">Approved At:</span>
            <span>{{ optional($submission->supervisor_approved_at)->format('F d, Y h:i A') ?? 'N/A' }}</span>
        </div>
        @if($submission->supervisor_feedback)
            <div class="info-row">
                <span class="label">Feedback:</span>
                <p>{{ $submission->supervisor_feedback }}</p>
            </div>
        @endif
    </div>
    @endif

    @if($submission->forwarded_to_dean_at || $submission->dean_feedback || $submission->dean)
    <div class="section">
        <div class="section-title">Dean Review</div>
        <div class="info-row">
            <span class="label">Forwarded At:</span>
            <span>{{ optional($submission->forwarded_to_dean_at)->format('F d, Y h:i A') ?? 'N/A' }}</span>
        </div>
        <div class="info-row">
            <span class="label">Dean:</span>
            <span>{{ $submission->dean->name ?? 'Pending review' }}</span>
        </div>
        <div class="info-row">
            <span class="label">Reviewed At:</span>
            <span>{{ optional($submission->dean_reviewed_at)->format('F d, Y h:i A') ?? 'N/A' }}</span>
        </div>
        @if($submission->dean_feedback)
            <div class="info-row">
                <span class="label">Feedback:</span>
                <p>{{ $submission->dean_feedback }}</p>
            </div>
        @endif
    </div>
    @endif

    <div class="footer">
        <p>This is an official OJT report generated by the OJT Approval System.</p>
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
    </div>
</body>
</html>
